### ISSUE TITLE
EpiCacheTypeDoesNotExistException

### ISSUE THREAD

**Issue by nvomedia** [jmathai/epiphany#103]
Hi, I'm trying this very simple and easy framework. I used the login example to create my first app with a form. Now I want to extend that example with a working form validation (does the user exists and is the password correct).
So I created an config file, loaded and want to get an user based on the input, but I'm getting an `EpiCacheTypeDoesNotExistException` error when I submitting the form.
The message is `Could not determine which database module to load`.

Since I using an ini file with the database details, how can I specify that I want to use mysql(i). Or is this message about something else?

This is my index.php
```
<?php
error_reporting(E_ALL);

include_once('/src/Epi.php');
include_once('controllers/Home.php');
include_once('controllers/Login.php');
include_once('controllers/Dashboard.php');
include_once('lib/const.php');

Epi::setSetting('exceptions', true);
Epi::SetPath('base', './src');
Epi::setPath('view', './views');
Epi::init('database','config', 'route', 'template', 'session');

//Configuration load
Epi::setPath('config', 'config');
getConfig()->load('development.ini');

getRoute()->get('/', array('HomeController', 'display'));
getRoute()->get('/login', array('LoginController', 'display'));
getRoute()->post('/login', array('LoginController', 'processLogin'));
getRoute()->get('/dashboard', array('DashboardController', 'display'));
getRoute()->get('/logout', array('LoginController', 'processLogout'));

getRoute()->run();

?>
```

And the processLogin function int he LoginController
```
static public function processLogin()
	{
		// Confirm the password is correct
		$email = $_POST['email'];
		$pass = sha1($_POST['pwd']);
		
		$user = getDatabase()->one('SELECT * FROM users WHERE user_email=:email AND user_password=:pwd', array(':email' => $email, ':pwd' => $password));
		
		echo $user;

		// * Assume it's all good for the time being * //
		// Redirect to the logged in home page
		getSession()->set(Constants::LOGGED_IN, true);
		//getRoute()->redirect('/epi/dashboard');
	}
```

**Comment by jmathai** [comment]
Can you paste in `development.ini` (leaving out any secrets)?

**Comment by nvomedia** [comment]
It contains the following lines (copied from the docs) :

dbhost = localhost
dbuser = root
dbpass = mypassword
dbname = mydb

**Comment by nvomedia** [comment]
Do you know more about this? Which config variables are missing in the ini?

**Comment by jmathai** [comment]
I don't see where you initialize the database module.

https://github.com/jmathai/epiphany/blob/master/examples/database/index.php#L6

**Comment by nvomedia** [comment]
Ow yeah.
Finally get this to work. 

```
//Configuration load
Epi::setPath('config', 'config');
getConfig()->load('development.ini');

$dbtype = getConfig()->get('dbtype');
$dbname = getConfig()->get('dbname');
$dbhost = getConfig()->get('dbhost');
$dbuser = getConfig()->get('dbuser');
$dbpass = getConfig()->get('dbpass');

//Database init
EpiDatabase::employ($dbtype,$dbname, $dbhost, $dbuser, $dbpass);
```
