### ISSUE TITLE
Api - No result when too much results

### ISSUE THREAD

**Issue by M01n34u** [jmathai/epiphany#104]
Hello ! 

When I make PDO request, I can have a lot of result, but nothing is returned. I tried to var_dump tht fetchall, no problem, I have everything. 
But in the end the API response is empty.

Thanks a lot

**Comment by jmathai** [comment]
Can you see if there is anything in your error logs? I suspect that you might be running out of memory if the result set is too large.

**Comment by M01n34u** [comment]
Ok, I found what is going wrong.
UTF8...
If I have a bad encode character in my function return, no output.

I have to `array_map_recursive("utf8_encode", $fetched_result)`
