### ISSUE TITLE
Not able to access the functions inside my class

### ISSUE THREAD

**Issue by imarshmultani** [jmathai/epiphany#99]
suppose i have the following code :

    class User {
    
     private $myvar;

    function __construct(){

    $myvar = 'some data';
    $this->myvar = 'some data';
    }

    // the below function is called from router
    public static function router_called_function(){
    echo $myvar;
    echo $this->myvar;
    }
    }

so as per the code when action 'router_called_function' is called i have to access the object : $myvar or $this->myvar  but it does not let me use it , it says :

Fatal error: Using $this when not in object context in

**Comment by jmathai** [comment]
When you call a method statically you can't use `$this` as there's no object context. You'll need to instantiate `User` first. Not sure if you meant to define the function statically or not.

```
$userObj = new User;
echo $userObj->router_called_function();
```

**Comment by imarshmultani** [comment]
but as i have described the problem , is it possible to avoid static ? and use normal public function or i have too call the class again n again inside functions to connect with other functions ? inside the same class?

**Comment by georules** [comment]
You can avoid using static if you instantiate an object of the class and then call the function from that object.
